Bitte schreibe den folgenden schwer verständlichen Text vollständig in Einfache Sprache, Sprachniveau B1 bis A2, um. 

Beachte dabei folgende Regeln für Einfache Sprache (B1 bis A2):

{completeness}
{rules}

Put your response between a <einfachesprache> and a </einfachesprache> tag.

Hier ist der schwer verständliche Text:

--------------------------------------------------------------------------------

{prompt}